version: '3.7'

services:
  mysql:
    image: mysql
    volumes:
      - ./db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'password'

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
    restart: always
    ports:
      - "8081:80"

  php:
    build:
      context: ./php7.2
      dockerfile: dockerfile
    volumes:
      - ./php7.2/php.ini:/usr/local/etc/php/php.ini
      - ./htdocs:/var/www/html
      - ./apache2/apache2.conf:/etc/apache2/apache2.conf
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - mysql

volumes:
    db_data: {}